-- ============================================================================
-- Datos iniciales: migración del contenido .md a las tablas de Supabase.
-- Ejecutar en Supabase Studio → SQL Editor DESPUÉS de haber ejecutado schema.sql.
--
-- Las URLs de cover_url son placeholders: sustitúyelas por las URLs reales
-- del bucket de Storage cuando subas las fotos definitivas.
-- Formato: https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/servicios/nombre.webp
-- ============================================================================

-- ── SERVICIOS ───────────────────────────────────────────────────────────────

INSERT INTO public.servicios (slug, title, short_title, seo_title, description, excerpt, cover_url, cover_alt, icon, "order", price_from, price_unit, duration, features, includes, faqs, body_md, draft, updated_at) VALUES

('reforma-integral',
 'Reforma integral de viviendas en Sabadell',
 'Reforma integral',
 'Reforma integral de pisos en Sabadell',
 'Reforma integral de pisos y casas en Sabadell con presupuesto cerrado, dirección de obra propia y 3 años de garantía. Proyecto llave en mano en 8-12 semanas.',
 'Rediseñamos tu vivienda completa con un único responsable de obra, presupuesto cerrado y plazos por escrito. Distribución, instalaciones, acabados y licencias.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/servicios/reforma-integral.webp',
 'Salón amplio y luminoso tras una reforma integral en Sabadell',
 'home', 1, 480, 'm²', '8-12 semanas',
 '["Presupuesto cerrado por partidas, sin sobrecostes","Jefe de obra asignado y parte semanal de avance","Gestión completa de licencias y trámites municipales","Industriales propios: sin subcontratas descontroladas","Garantía de 3 años sobre instalaciones y acabados"]',
 '["Levantamiento y proyecto técnico con planos de distribución","Demolición, retirada de escombros y gestión de residuos","Renovación de fontanería, saneamiento y electricidad certificada","Albañilería, solados, alicatados, carpintería y pintura","Limpieza final de obra y certificados de instalación"]',
 '[{"question":"¿Cuánto cuesta una reforma integral en Sabadell?","answer":"Una reforma integral de calidad media-alta en Sabadell parte de 480 €/m² e incluye instalaciones nuevas, albañilería, carpintería y acabados. En una vivienda de 90 m² el rango habitual es de 43.000 € a 68.000 € según nivel de acabados y estado de partida."},{"question":"¿Cuánto tarda una reforma integral de un piso?","answer":"Entre 8 y 12 semanas para viviendas de 70 a 120 m² sin cambios estructurales. Si hay que abrir huecos en muros de carga o tramitar licencia de obra mayor, el plazo se amplía de 3 a 6 semanas por los trámites técnicos."},{"question":"¿Puedo vivir en la casa mientras dura la obra?","answer":"No lo recomendamos en una reforma integral porque se retiran instalaciones, baños y cocina. Si es imprescindible, planificamos la obra por fases dejando siempre un baño operativo, aunque el plazo total aumenta alrededor de un 30 %."},{"question":"¿Qué licencias necesita una reforma integral?","answer":"En Sabadell la mayoría de reformas sin afectación estructural se tramitan como declaración responsable. Si se modifican elementos comunes, fachada o estructura hace falta licencia de obra mayor con proyecto de arquitecto. Nos encargamos de todo el trámite."}]',
 E'## Una sola empresa responsable de toda la obra\n\nCoordinar por tu cuenta a fontaneros, electricistas, albañiles y carpinteros es la causa número uno de retrasos y sobrecostes en una reforma. Nosotros asumimos la obra completa: un contrato, un presupuesto cerrado y un jefe de obra que responde por el resultado final.\n\n## Cómo trabajamos tu reforma integral\n\n1. **Visita técnica y medición.** Revisamos estado de instalaciones, humedades, muros de carga y posibilidades reales de redistribución.\n2. **Proyecto y presupuesto cerrado.** Recibes planos de distribución y un presupuesto desglosado por partidas con calidades y marcas concretas.\n3. **Planificación de la obra.** Calendario por semanas con hitos verificables y fecha de entrega comprometida en contrato.\n4. **Ejecución con control diario.** Parte de avance semanal con fotografías y reuniones de obra para validar acabados antes de instalarlos.\n5. **Entrega y garantía.** Repaso final con lista de remates, certificados de instalación y 3 años de garantía por escrito.\n\n## Reformas estructurales y redistribución\n\nAbrir la cocina al salón, ganar un segundo baño o eliminar pasillos inútiles requiere estudiar la estructura del edificio. Trabajamos con arquitecto e ingeniero para calcular refuerzos, tramitar la licencia y ejecutar la apertura de huecos con las medidas de seguridad y los apuntalamientos necesarios.\n\n## Materiales y acabados\n\nSeleccionamos materiales con criterio de durabilidad y mantenimiento, no solo estético: porcelánico rectificado en zonas húmedas, suelo laminado AC5 o tarima de madera en estancias, carpintería con rotura de puente térmico y pintura plástica lavable. Todo queda especificado en el presupuesto para que sepas exactamente qué se instala en tu casa.',
 false, '2025-11-18'::timestamptz),

('reforma-de-cocinas',
 'Reforma de cocinas en Sabadell',
 'Cocinas',
 'Reforma de cocinas en Sabadell',
 'Reformamos tu cocina en 3-4 semanas con diseño 3D, mobiliario a medida e instalaciones nuevas. Presupuesto cerrado, montaje propio y garantía de 3 años.',
 'Diseño 3D antes de empezar, mobiliario a medida, encimeras técnicas e instalaciones renovadas. Cocinas abiertas o cerradas ejecutadas en 3-4 semanas.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/servicios/reforma-de-cocinas.webp',
 'Cocina reformada con isla central y muebles a medida en Sabadell',
 'kitchen', 2, 7900, 'cocina', '3-4 semanas',
 '["Diseño 3D previo para validar distribución y acabados","Mobiliario a medida con herrajes de cierre amortiguado","Encimeras en porcelánico, compac o cuarzo técnico","Electricidad y fontanería nuevas con circuitos independientes","Coordinación de electrodomésticos y puesta en marcha"]',
 '["Retirada de mobiliario antiguo y gestión de residuos","Nueva instalación eléctrica con protecciones y tomas suficientes","Fontanería y desagües renovados con llaves de corte accesibles","Alicatado o revestimiento continuo y frente de cocina","Montaje de muebles, encimera, fregadero y grifería"]',
 '[{"question":"¿Cuánto cuesta reformar una cocina en Sabadell?","answer":"Una reforma de cocina completa con mobiliario, encimera técnica, instalaciones nuevas y alicatado parte de 7.900 € para unos 8 m². El rango más habitual está entre 9.500 € y 16.000 € según encimera, herrajes y electrodomésticos."},{"question":"¿Cuánto tiempo estaré sin cocina?","answer":"El plazo medio es de 3 a 4 semanas. Las dos primeras corresponden a demolición e instalaciones, y las siguientes al alicatado y montaje de mobiliario. Dejamos siempre operativos el frigorífico y un punto de agua provisional."},{"question":"¿Merece la pena abrir la cocina al salón?","answer":"Gana luz natural y sensación de amplitud, y es la intervención con mayor impacto en el valor de la vivienda. Requiere comprobar si el tabique es de carga y prever una campana de extracción con salida a shunt o recirculación con filtros de carbón."},{"question":"¿Qué encimera aguanta mejor el uso diario?","answer":"El porcelánico y el cuarzo técnico son los más resistentes a rayado, calor y manchas. La madera exige mantenimiento con aceite cada 6-12 meses y el mármol es delicado con ácidos como el limón o el vinagre."}]',
 E'## El diseño se decide antes de tocar la obra\n\nAntes de demoler nada modelamos tu cocina en 3D con las medidas reales tomadas en obra. Validamos alturas de trabajo, recorridos entre fregadero, placa y frigorífico, y el número de tomas eléctricas necesarias. Aprobar el diseño en pantalla evita el 90 % de los cambios caros a mitad de obra.\n\n## Instalaciones: la parte que no se ve\n\nUna cocina moderna concentra más consumo eléctrico que el resto de la vivienda. Renovamos el circuito con línea independiente para horno, vitrocerámica y lavavajillas, protecciones diferenciales adecuadas y tomas útiles sobre la encimera. En fontanería sustituimos tubería por multicapa o polietileno reticulado y dejamos llaves de corte accesibles bajo el fregadero.\n\n## Almacenaje aprovechado al centímetro\n\nColumnas hasta el techo, cajones con guías de extracción total, esquineros extraíbles y zócalos con cajón oculto. En cocinas pequeñas el orden lo da el mobiliario a medida, no la superficie: por eso fabricamos cada módulo con las dimensiones exactas del hueco disponible.\n\n## Ventilación y climatización\n\nCalculamos la campana según el caudal necesario y la longitud del conducto. Cuando no hay salida a shunt planteamos recirculación con filtros de carbón activo y refuerzo de ventilación, cumpliendo el CTE HS3 de calidad del aire interior.',
 false, '2025-11-18'::timestamptz),

('reforma-de-banos',
 'Reforma de baños en Sabadell',
 'Baños',
 'Reforma de baños en Sabadell en 2 semanas',
 'Reforma de baños en Sabadell en 10-15 días: cambio de bañera por plato de ducha, impermeabilización certificada y saneamiento nuevo. Presupuesto cerrado.',
 'Baños funcionales y estancos ejecutados en 10-15 días. Cambio de bañera por ducha, impermeabilización garantizada y ventilación forzada silenciosa.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/servicios/reforma-de-banos.webp',
 'Baño reformado con plato de ducha de obra y mampara de cristal',
 'droplet', 3, 4600, 'baño', '10-15 días',
 '["Impermeabilización con lámina líquida bajo alicatado","Cambio de bañera por plato de ducha antideslizante","Saneamiento y desagües renovados con pendientes correctas","Ventilación forzada silenciosa y suelo radiante opcional","Soluciones accesibles sin barreras arquitectónicas"]',
 '["Demolición de sanitarios, alicatado y solado existentes","Fontanería nueva con llaves de corte por estancia","Impermeabilización de plato de ducha y paramentos húmedos","Alicatado, solado y sellados sanitarios","Montaje de sanitarios, grifería, mampara y mobiliario"]',
 '[{"question":"¿Cuánto cuesta reformar un baño en Sabadell?","answer":"Un baño completo de 4-5 m² con plato de ducha, mueble, sanitarios de marca e impermeabilización parte de 4.600 €. Con acabados de gama alta, ducha a ras de suelo y suelo radiante el rango sube a 6.500-9.000 €."},{"question":"¿Cuánto se tarda en reformar un baño?","answer":"Entre 10 y 15 días laborables. La impermeabilización y los sellados necesitan tiempos de curado que no se pueden acelerar sin arriesgar filtraciones al vecino, así que no comprimimos ese plazo."},{"question":"¿Se puede cambiar la bañera por ducha sin obra?","answer":"Existen sustituciones rápidas en 1-2 días con plato sobre el hueco de la bañera, pero solo son recomendables si el saneamiento está en buen estado. Si hay tubería de plomo o fibrocemento, conviene renovar la instalación completa."},{"question":"¿Cómo evitáis filtraciones al vecino de abajo?","answer":"Aplicamos lámina impermeabilizante líquida con banda elástica en encuentros suelo-pared, probamos el desagüe con agua durante 24 horas antes de alicatar y sellamos con silicona neutra sanitaria de larga duración."}]',
 E'## Un baño falla por lo que no se ve\n\nLa mayoría de reclamaciones en reformas de baño no son estéticas: son filtraciones. Por eso impermeabilizamos con lámina líquida el plato de ducha y todos los paramentos que reciben agua, reforzamos los encuentros con banda elástica y probamos el desagüe antes de cerrar el alicatado.\n\n## De bañera a ducha, con criterio\n\nSustituir la bañera por una ducha amplia gana espacio y accesibilidad. Podemos ejecutar plato de obra revestido en porcelánico continuo, plato extraplano de resina o ducha a ras de suelo cuando la altura del forjado lo permite. En viviendas con personas mayores añadimos asideros, banco abatible y suelo antideslizante clase 3.\n\n## Instalaciones y confort\n\nRenovamos fontanería con tubería multicapa, colocamos llaves de corte accesibles y dimensionamos la evacuación con pendientes correctas para evitar malos olores. Como extras habituales instalamos suelo radiante eléctrico bajo el porcelánico, toallero de agua caliente y extractor con temporizador silencioso.\n\n## Almacenaje en pocos metros\n\nMueble suspendido de fácil limpieza, espejo con armario integrado, nichos alicatados en la ducha y columnas estrechas aprovechando huecos muertos. En baños de 3-4 m² cada centímetro cuenta y el mobiliario a medida marca la diferencia.',
 false, '2025-11-18'::timestamptz);
