-- ── PROYECTOS (parte 2) ─────────────────────────────────────────────────────

INSERT INTO public.proyectos (slug, title, description, excerpt, cover_url, cover_alt, servicio_slug, location, year, surface, duration, budget_range, highlights, testimonial, featured, "order", body_md, draft, updated_at) VALUES

('bano-spa-pozuelo',
 'Baño tipo spa en vivienda de Pozuelo',
 'Reforma de baño principal de 8 m² en Pozuelo de Alarcón con ducha a ras de suelo, suelo radiante y doble lavabo suspendido en 12 días.',
 'Baño principal convertido en zona de descanso con ducha de obra a ras de suelo, microcemento hidrófugo y suelo radiante eléctrico.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/bano-spa-pozuelo.webp',
 'Baño reformado tipo spa con ducha a ras de suelo y doble lavabo',
 'reforma-de-banos',
 'Pozuelo de Alarcón', 2025, 8, '12 días', '9.200 € - 10.500 €',
 '["Ducha a ras de suelo de 1,6 m con rejilla lineal","Impermeabilización líquida con prueba de estanqueidad de 24 h","Suelo radiante eléctrico bajo porcelánico rectificado","Doble lavabo suspendido con mueble a medida"]',
 '{"quote":"Nos avisaron de que la impermeabilización necesitaba tiempo de curado y preferimos esperar. Un año después, cero problemas y el vecino de abajo tranquilo.","author":"Ana M.","role":"Propietaria","rating":5}',
 false, 4,
 E'## Punto de partida\n\nBaño de 8 m² con bañera de 1,7 m infrautilizada, un solo lavabo y alicatado original de 1998. El desagüe de la bañera presentaba humedades en el techo del piso inferior.\n\n## Intervención\n\nSustitución de la bañera por una ducha de obra a ras de suelo con rejilla lineal oculta, impermeabilización líquida en todos los paramentos húmedos y prueba de estanqueidad de 24 horas antes del alicatado. Se instaló suelo radiante eléctrico bajo porcelánico rectificado de gran formato y un mueble suspendido a medida con doble seno.\n\n## Resultado\n\nUn baño con estética continua, mantenimiento mínimo y accesibilidad total al no existir escalón en la zona de ducha. La humedad del piso inferior se resolvió al renovar el desagüe y la impermeabilización.',
 false, '2025-11-18'::timestamptz),

('clinica-dental-alcobendas',
 'Clínica dental de nueva apertura en Alcobendas',
 'Adecuación de local de 180 m² en Alcobendas para clínica dental: cuatro gabinetes, sala de esterilización, licencia sanitaria y obra en 9 semanas.',
 'Local diáfano transformado en clínica dental con cuatro gabinetes, zona de esterilización, radiología protegida y accesibilidad completa.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/clinica-dental-alcobendas.webp',
 'Recepción de clínica dental reformada con iluminación técnica',
 'reforma-de-locales-comerciales',
 'Alcobendas', 2024, 180, '9 semanas', '168.000 € - 180.000 €',
 '["Cuatro gabinetes con instalación de aire comprimido y aspiración","Sala de radiología con blindaje de plomo certificado","Aislamiento acústico DB-HR entre gabinetes","Aseo adaptado e itinerario accesible completo"]',
 '{"quote":"Coordinaron la obra con el proveedor de los equipos dentales y con la tramitación sanitaria. Abrimos en la fecha prevista, que era lo crítico para nosotros.","author":"Dr. Pablo S.","role":"Director de la clínica","rating":5}',
 false, 5,
 E'## Punto de partida\n\nLocal comercial diáfano de 180 m² en planta baja, sin instalaciones más allá de la acometida eléctrica y un aseo, con licencia de actividad pendiente de tramitar.\n\n## Intervención\n\nProyecto de adecuación completo: distribución con tabiquería seca y aislamiento acústico entre gabinetes, sala de esterilización con circuito sucio-limpio diferenciado, sala de radiología con blindaje certificado, climatización por conductos con renovación de aire y cableado estructurado categoría 6A. Se tramitaron licencia de actividad y autorización sanitaria en paralelo a la obra.\n\n## Resultado\n\nClínica operativa en 9 semanas, con cuatro gabinetes preparados para los equipos del fabricante, itinerario accesible desde la calle y toda la documentación lista para la inspección municipal y sanitaria.',
 false, '2025-11-18'::timestamptz),

('fachada-getafe',
 'Rehabilitación de fachada con SATE en Getafe',
 'Rehabilitación energética de fachada de 1.250 m² en Getafe con SATE, reparación de balcones y subvención del 60 % para la comunidad de propietarios.',
 'Edificio de 32 viviendas con aislamiento exterior SATE, reparación de cantos de forjado y mejora de dos letras en la calificación energética.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/fachada-getafe.webp',
 'Fachada de edificio rehabilitada con sistema de aislamiento exterior',
 'rehabilitacion-de-fachadas',
 'Getafe', 2024, 1250, '13 semanas', '142.000 € - 155.000 €',
 '["SATE de 80 mm en EPS grafitado sobre soporte regularizado","Reparación de armaduras oxidadas en cantos de forjado","Subvención tramitada del 60 % del coste de la obra","Mejora de la calificación energética de E a C"]',
 '{"quote":"Explicaron el proyecto en junta con números claros y gestionaron la subvención. El primer invierno se notó de verdad en la factura de calefacción.","author":"Comunidad de propietarios","role":"Getafe centro","rating":5}',
 false, 6,
 E'## Punto de partida\n\nEdificio de 32 viviendas construido en 1974, sin aislamiento en fachada, con desprendimientos puntuales de mortero, armaduras oxidadas visibles en cantos de forjado y calificación energética E.\n\n## Intervención\n\nMontaje de andamio homologado con plan de seguridad, saneado de zonas degradadas y pasivado de armaduras, regularización del soporte y colocación de SATE con 80 mm de EPS grafitado, malla de refuerzo, mortero y acabado elástico transpirable. Se repararon 24 balcones con impermeabilización y goterón nuevo.\n\n## Resultado\n\nReducción estimada del 38 % en demanda de calefacción, subida de la calificación energética de E a C y eliminación de condensaciones interiores en las viviendas de esquina. La comunidad obtuvo una subvención del 60 % del coste total.',
 false, '2025-11-18'::timestamptz);
