-- ── PROYECTOS (parte 1) ─────────────────────────────────────────────────────

INSERT INTO public.proyectos (slug, title, description, excerpt, cover_url, cover_alt, servicio_slug, location, year, surface, duration, budget_range, highlights, testimonial, featured, "order", body_md, draft, updated_at) VALUES

('atico-chamberi',
 'Reforma integral de ático en Chamberí',
 'Reforma integral de un ático de 96 m² en Chamberí con apertura de cocina al salón, dos baños nuevos y climatización por conductos en 10 semanas.',
 'Vivienda de 1962 sin reformar. Se abrió la cocina al salón, se redistribuyó la zona de noche para ganar un segundo baño y se renovaron todas las instalaciones.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/atico-chamberi.webp',
 'Salón de ático reformado en Chamberí con acceso a terraza',
 'reforma-integral',
 'Chamberí, Sabadell', 2025, 96, '10 semanas', '68.000 € - 74.000 €',
 '["Apertura de muro de carga con refuerzo metálico calculado","Segundo baño ganado en el hueco del pasillo","Suelo radiante eléctrico en baños y tarima de roble en estancias","Climatización por conductos con control por zonas"]',
 '{"quote":"Nos dieron una fecha de entrega y la cumplieron con dos días de adelanto. El parte semanal con fotos nos permitió seguir la obra desde el trabajo sin agobios.","author":"Marta G.","role":"Propietaria del ático","rating":5}',
 true, 1,
 E'## Punto de partida\n\nUn ático de 1962 que conservaba la distribución original: cocina cerrada de 6 m², pasillo de reparto de casi 9 m² y un único baño para tres dormitorios. La instalación eléctrica seguía siendo monofásica con cableado de 1,5 mm² y las bajantes originales presentaban filtraciones.\n\n## Intervención\n\nSe eliminó el tabique entre cocina y salón mediante apertura de hueco en muro de carga con perfil metálico calculado por el ingeniero de estructuras y licencia de obra mayor. El pasillo se acortó para insertar un segundo baño completo, y se renovaron por completo fontanería, saneamiento y electricidad.\n\n## Resultado\n\nLa vivienda pasó de 5 estancias compartimentadas a un espacio de día unificado de 34 m² con salida a terraza. El consumo de climatización bajó gracias a la sustitución de carpintería por aluminio con rotura de puente térmico y vidrio bajo emisivo.',
 false, '2025-11-18'::timestamptz),

('piso-salamanca',
 'Piso clásico reformado en Barrio de Salamanca',
 'Reforma integral de 140 m² en el Barrio de Salamanca respetando molduras y carpintería original, con instalaciones nuevas y cocina office a medida.',
 'Rehabilitación de una vivienda señorial conservando molduras, suelos de tarima y puertas originales, con instalaciones y baños completamente nuevos.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/piso-salamanca.webp',
 'Salón señorial reformado con molduras restauradas en el Barrio de Salamanca',
 'reforma-integral',
 'Barrio de Salamanca, Sabadell', 2024, 140, '14 semanas', '112.000 € - 120.000 €',
 '["Restauración de molduras de escayola y rosetones originales","Recuperación y barnizado de tarima de pino mobila","Tres baños nuevos con impermeabilización certificada","Cocina office a medida con despensa integrada"]',
 '{"quote":"Buscábamos alguien capaz de modernizar sin destrozar el carácter del piso. Restauraron las molduras y las puertas originales en lugar de sustituirlas, que era lo fácil.","author":"Javier R.","role":"Propietario","rating":5}',
 true, 2,
 E'## Punto de partida\n\nVivienda de 1908 con elementos originales de valor (molduras, rosetones, puertas de dos hojas y tarima de pino mobila) pero con instalaciones de los años setenta, tres baños obsoletos y una cocina desconectada de la zona de día.\n\n## Intervención\n\nEl criterio fue conservar y restaurar todo lo recuperable. Se desmontaron y numeraron las puertas para su decapado y barnizado en taller, se reprodujeron los tramos de moldura perdidos con molde propio y se acuchilló la tarima existente en lugar de sustituirla. Las instalaciones se renovaron íntegramente por falsos techos perimetrales para no romper las escayolas históricas.\n\n## Resultado\n\nUn piso con confort actual (climatización por conductos, domótica de iluminación, tres baños nuevos) que mantiene intacta la identidad del edificio. La obra se ejecutó en 14 semanas coordinando restaurador, carpintería de taller y gremios propios.',
 false, '2025-11-18'::timestamptz),

('cocina-abierta-retiro',
 'Cocina abierta con isla en Retiro',
 'Reforma de cocina de 14 m² en el barrio de Retiro con isla central, encimera de porcelánico y apertura al salón ejecutada en cuatro semanas.',
 'Cocina cerrada convertida en espacio abierto con isla de trabajo, columnas hasta el techo y campana de extracción integrada.',
 'https://donirysodidyakcmsfhc.supabase.co/storage/v1/object/public/imagenes/proyectos/cocina-abierta-retiro.webp',
 'Cocina abierta con isla central y encimera de porcelánico en Retiro',
 'reforma-de-cocinas',
 'Retiro, Sabadell', 2025, 14, '4 semanas', '18.500 € - 21.000 €',
 '["Isla de 2,4 m con placa de inducción y extracción perimetral","Encimera de porcelánico de 12 mm con canto recto","Circuitos eléctricos independientes para cada electrodoméstico","Iluminación en tres niveles: general, trabajo y ambiente"]',
 '{"quote":"El diseño 3D nos ahorró discusiones: vimos la cocina terminada antes de empezar y el resultado final es idéntico al render.","author":"Lucía y Andrés","role":"Propietarios","rating":5}',
 true, 3,
 E'## Punto de partida\n\nCocina cerrada de 9 m² con office separado por un tabique no estructural, mobiliario de los años noventa y una única toma de corriente sobre la encimera.\n\n## Intervención\n\nSe unificaron cocina y office eliminando el tabique intermedio y se abrió un hueco de paso de 2,10 m hacia el salón. El mobiliario se fabricó a medida con columnas hasta el techo y una isla de 2,4 m que integra placa de inducción, extracción perimetral y cajones profundos. Se renovó la instalación eléctrica con líneas independientes para horno, lavavajillas e inducción.\n\n## Resultado\n\nUna cocina de 14 m² conectada visualmente con el salón, con 4,8 m lineales de almacenaje y triángulo de trabajo optimizado entre fregadero, placa y frigorífico.',
 false, '2025-11-18'::timestamptz);
